stages:
  - build
  - doc

gcc-9:
  stage: build
  image: conanio/gcc9
  variables:
    CONAN_USERNAME: "${CI_PROJECT_ROOT_NAMESPACE}+${CI_PROJECT_NAME}"
    CONAN_CHANNEL: "testing"
    CONAN_LOGIN_USERNAME: "ci_user"
    CONAN_PASSWORD: "${CI_JOB_TOKEN}"
    CONAN_UPLOAD: "${CI_API_V4_URL}/packages/conan@True@gitlab"
  before_script:
    - sudo pip install --upgrade conan_package_tools
  script:
    - python build.py

doc:
  stage: doc
  image: sphinxdoc/sphinx
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  before_script:
    - pip3 install conan breathe sphinx-substitution-extensions
    - apt-get update
    - apt-get install --no-install-recommends -y cmake gcc doxygen
  script:
    - mkdir build
    - cmake -S . -B build -DQSETTINGSCONTAINER_BUILD_DOC=On
    - cd build
    - make
    - cp -Rv doc/html ${CI_PROJECT_DIR}/public
  artifacts:
    paths:
      - public
