variables:
  CONAN_USERNAME: "${CI_PROJECT_ROOT_NAMESPACE}+${CI_PROJECT_NAME}"
  CONAN_CHANNEL: "testing"
  CONAN_LOGIN_USERNAME: "ci_user"
  CONAN_PASSWORD: "${CI_JOB_TOKEN}"
  CONAN_REMOTES: "${CI_API_V4_URL}/packages/conan@True@gitlab"

gcc-9:
  image: conanio/gcc9
  before_script:
    - sudo pip install --upgrade conan_package_tools
  script:
    - python build.py
